import Foundation

public struct ChannelObject: Hashable, Decodable {
    public var type = ResultType.channel
    public var author: String
    public var authorId: String
    public var authorUrl: String
    public var authorVerified: Bool
    public var authorThumbnails: [ImageObject]
    public var autoGenerated: Bool
    public var subCount: Int
    public var videoCount: Int
    public var description: String
    
    public static func == (lhs: ChannelObject, rhs: ChannelObject) -> Bool {
        lhs.authorId == rhs.authorId
    }
}
